version: '{build}'

image:
  - Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    # Visual Studio 2015
#    - TOOLCHAIN: v140
#      STD: 14
    # Visual Studio 2017
    - TOOLCHAIN: v141
      STD: 14
    - TOOLCHAIN: v141
      STD: 17
    # Visual Studio 2019
    - TOOLCHAIN: v142
      STD: 14
    - TOOLCHAIN: v142
      STD: 17

init:
  - cmake --version
  - msbuild /version

before_build:
  - mkdir -p build
  - cd build
  - cmake .. -A %PLATFORM% -T %TOOLCHAIN% -DCMAKE_CXX_STANDARD=%STD%

build_script:
  - cmake --build . --config %CONFIGURATION% -- -verbosity:n

test_script:
  - ctest -C %CONFIGURATION% -V -j
