name: Single Include

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: update single include
      run: |
        mv single_include/inja/inja.hpp single_include/inja/inja_old.hpp
        bash scripts/update_single_include.sh

    - name: check if equal
      working-directory: ${{runner.workspace}}/inja/single_include/
      shell: bash
      run: |
        diff inja/inja.hpp inja/inja_old.hpp >/dev/null

    - uses: actions/upload-artifact@v1
      with:
        name: single_include_inja
        path: single_include/inja/inja.hpp
